# Generated by Django 4.2.1 on 2023-06-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("receipts", "0003_alter_receipt_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receipt",
            name="date",
            field=models.DateTimeField(null=True),
        ),
    ]
